export const ACCOUNT_LOGOS: string[] = [
    '/accounts/shopee.webp',
    '/accounts/gopay.webp',
    '/accounts/bca.webp',
    '/accounts/wallet.webp',
    '/accounts/ovo.webp',
    '/accounts/dana.webp',
    '/accounts/bri.webp',
    '/accounts/invest.webp',
    '/accounts/loan.webp',
    '/accounts/bni.webp',
    '/accounts/livin-mandiri.webp',
] as const;

export const CATEGORY_LOGOS: string[] = [
    '/categories/bill.webp',
    '/categories/education.webp',
    '/categories/future.webp',
    '/categories/health.webp',
    '/categories/internet.webp',
    '/categories/laundry.webp',
    '/categories/rent.webp',
    '/categories/salary.webp',
    '/categories/snack.webp',
    '/categories/sport.webp',
    '/categories/support.webp',
    '/categories/transportation.webp',
    '/categories/coupon.webp',
    '/categories/food.webp',
    '/categories/grants.webp',
    '/categories/insurance.webp',
    '/categories/invest.webp',
    '/categories/refund.webp',
    '/categories/reward.webp',
    '/categories/shopping.webp',
    '/categories/social.webp',
    '/categories/subscription.webp',
    '/categories/tax.webp',
] as const;
