export const AccountLogo: string[] = [
    'https://placehold.co/100',
    'https://placehold.co/100',
    'https://placehold.co/100',
    'https://placehold.co/100',
    'https://placehold.co/100',
    'https://placehold.co/100',
    'https://placehold.co/100',
    'https://placehold.co/100',
    'https://placehold.co/100',
    'https://placehold.co/100',
    'https://placehold.co/100',
    'https://placehold.co/100',
    'https://placehold.co/100',
    'https://placehold.co/100',
    'https://placehold.co/100',
    'https://placehold.co/100',
    'https://placehold.co/100',
    'https://placehold.co/100',
    'https://placehold.co/100',
    'https://placehold.co/100',
    'https://placehold.co/100',
    'https://placehold.co/100',
    'https://placehold.co/100',
    'https://placehold.co/100',
    'https://placehold.co/100',
] as const;
