export const ACCOUNT_LOGOS: string[] = [
    '/accounts/shopee.webp',
    '/accounts/gopay.webp',
    '/accounts/bca.webp',
    '/accounts/wallet.webp',
    '/accounts/ovo.webp',
    '/accounts/dana.webp',
    '/accounts/bri.webp',
    '/accounts/invest.webp',
    '/accounts/loan.webp',
] as const;

export const CATEGORY_LOGOS: string[] = [
    '/categories/bill.png',
    '/categories/education.png',
    '/categories/future.png',
    '/categories/health.png',
    '/categories/internet.png',
    '/categories/laundry.png',
    '/categories/rent.png',
    '/categories/salary.png',
    '/categories/snack.png',
    '/categories/sport.png',
    '/categories/support.png',
    '/categories/transportation.png',
    '/categories/coupon.png',
    '/categories/food.png',
    '/categories/grants.png',
    '/categories/insurance.png',
    '/categories/invest.png',
    '/categories/refund.png',
    '/categories/reward.png',
    '/categories/shopping.png',
    '/categories/social.png',
    '/categories/subscription.png',
    '/categories/tax.png',
] as const;
